### ISSUE TITLE
e2e tests are failing in master

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#512]
![image](https://cloud.githubusercontent.com/assets/959972/5477059/0d698ddc-85e5-11e4-9e02-b32edf7ffb6e.png)

Likely sources of the failures are these lines:

Error: Timed out waiting for Protractor to synchronize with the page after 11 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md

     TypeError: Object #<Object> has no method 'getInstance'
    at [object Object].<anonymous> (/Users/katowulf/gh/angularfire-master/tests/protractor/chat/chat.spec.js:6:25)
    at Object.<anonymous> (/Users/katowulf/gh/angularfire-master/tests/protractor/chat/chat.spec.js:4:1)

**Comment by jwngr** [comment]
These fail no longer (at least for Kato, James, and I)!!! Closing now.
