### ISSUE TITLE
ArraySyncManager, TypeError: Cannot read property '$$error' of null

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#589]
TypeError: Cannot read property '$$error' of null
    at https://cdn.firebase.com/libs/angularfire/1.0.0/angularfire.min.js:12:1722
    at https://cdn.firebase.com/libs/angularfire/1.0.0/angularfire.min.js:12:17446
    at Array.forEach (native)
    at Object.forEach (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.js:300:11)
    at g (https://cdn.firebase.com/libs/angularfire/1.0.0/angularfire.min.js:12:17419)
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.js:13200:28
    at completeOutstandingRequest (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.js:4003:10)
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.js:4309:7

**Comment by katowulf** [comment]
Occurs when attempting to access data which is restricted and getting permission_denied.

**Comment by mikepugh** [comment]
I've been seeing this a lot as I deal w/ permission_denied issue
